<a href="https://colab.research.google.com/github/Ahsa-n/ML-TOPPERS/blob/main/Day%204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 220, 250, 210, 180, 190],  # Day 1
    [230, 240, 260, 200, 195, 205],  # Day 2
    [210, 215, 255, 220, 185, 200],  # Day 3
    [205, 225, 270, 215, 190, 195],  # Day 4
    [215, 230, 265, 225, 200, 210],  # Day 5
    [225, 235, 275, 230, 205, 215],  # Day 6
    [235, 245, 280, 240, 210, 220],  # Day 7
    [245, 255, 290, 250, 215, 225],  # Day 8
    [255, 265, 300, 260, 220, 230],  # Day 9
    [265, 275, 310, 270, 225, 235],  # Day 10
])
#q1 a)
totalsaleperproduct = np.sum(sales_data,axis=0)
for i,x in enumerate(totalsaleperproduct):
  print(f"total sale of product no {i+1}: {x}")
#b)
for i,x in enumerate(totalsaleperproduct):
  print(f"average daily sale of product no {i+1}: {x/10:.2f}")
#c)
newsales_data= sales_data * 1.05
print(newsales_data)
#d)
newsales_data = np.sqrt(sales_data)
print(np.round(newsales_data,2))

#q2 a)
bonus_array = np.array([10,20,15,25,30,5])
newsales_data = sales_data + bonus_array
print(np.round(newsales_data,2))
#b)
newsales_data= sales_data + 50
print(np.round(newsales_data,2))
#q3 a)
print(f"mean: {np.mean(sales_data)}\nmedian: {np.median(sales_data)}\nvariance: {np.var(sales_data)}\nsd: {np.std(sales_data)} ")
#b)
print(f"max = {np.max(sales_data)}\nmin = {np.min(sales_data)}\nrange = {np.max(sales_data) - np.min(sales_data)}")
#c)
q1 = np.percentile(sales_data,25)
q3 = np.percentile(sales_data,75)
iqr = q3-q1
print(f"iqr: {iqr}")
#q4 a)
newarr = sales_data > 250
newsales=  sales_data[newarr]
print(newsales)
#b)
newarr = sales_data>300
sales_data[newarr] = 300
print(sales_data[newarr])
#c)
newarr = (sales_data>= 200) & (sales_data<= 250)
print(np.count_nonzero(sales_data[newarr]))
#d)
newarr = sales_data < np.mean(sales_data)
modifiedarr = sales_data[newarr]
print(modifiedarr)
print(sales_data)
print(np.mean(sales_data))
#q5
#a)
print(np.sort(sales_data[4]))
#b)
sumarr= np.sum(sales_data,axis = 1)
print(f"day: {np.argmax(sumarr) +1}")
#c)
print(np.mean(sales_data,axis = 0))
#d)
print(np.round(np.mean(sales_data,axis =1),2))
#e)
overall_average = np.mean(sales_data)
print(f"Overall average sales: {overall_average:.2f}")
#q6
def highlight_outliers(data):
  tempmean = np.mean(data)
  sd = np.std(data)
  outlier = (tempmean + 2*sd >data) & (tempmean- 2*sd <data)
  return data[outlier]
print(highlight_outliers(sales_data))

total sale of product no 1: 2285
total sale of product no 2: 2405
total sale of product no 3: 2755
total sale of product no 4: 2320
total sale of product no 5: 2025
total sale of product no 6: 2125
average daily sale of product no 1: 228.50
average daily sale of product no 2: 240.50
average daily sale of product no 3: 275.50
average daily sale of product no 4: 232.00
average daily sale of product no 5: 202.50
average daily sale of product no 6: 212.50
[[210.   231.   262.5  220.5  189.   199.5 ]
 [241.5  252.   273.   210.   204.75 215.25]
 [220.5  225.75 267.75 231.   194.25 210.  ]
 [215.25 236.25 283.5  225.75 199.5  204.75]
 [225.75 241.5  278.25 236.25 210.   220.5 ]
 [236.25 246.75 288.75 241.5  215.25 225.75]
 [246.75 257.25 294.   252.   220.5  231.  ]
 [257.25 267.75 304.5  262.5  225.75 236.25]
 [267.75 278.25 315.   273.   231.   241.5 ]
 [278.25 288.75 325.5  283.5  236.25 246.75]]
[[14.14 14.83 15.81 14.49 13.42 13.78]
 [15.17 15.49 16.12 14.14 13.96 14.32]
 [14.49 14.66 1